
var tabelaPrecos = {
    "guarda-roupa-solteiro": {
        nome: "Guarda-roupa Solteiro",
        icone: "🚪",
        categoria: "quarto",
        complexidade: "media",
        tempoMin: 180,
        tempoMax: 300,
        precoMin: 250,
        precoMax: 500,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Guarda-roupas solteiros exigem cuidado com nivelamento e alinhamento de portas."
    },
    "guarda-roupa-casal": {
        nome: "Guarda-roupa Casal",
        icone: "🚪",
        categoria: "quarto",
        complexidade: "alta",
        tempoMin: 240,
        tempoMax: 480,
        precoMin: 350,
        precoMax: 700,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Móveis grandes podem exigir mais de um profissional. Verifique o espaço disponível."
    },
    "guarda-roupa-correr": {
        nome: "Guarda-roupa Portas de Correr",
        icone: "🚪",
        categoria: "quarto",
        complexidade: "alta",
        tempoMin: 300,
        tempoMax: 480,
        precoMin: 450,
        precoMax: 850,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Portas de correr exigem maior tempo de regulagem e ajuste fino dos trilhos."
    },
    "comoda": {
        nome: "Cômoda",
        icone: "🗄️",
        categoria: "quarto",
        complexidade: "media",
        tempoMin: 60,
        tempoMax: 120,
        precoMin: 180,
        precoMax: 350,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "O número de gavetas influencia diretamente no tempo de montagem."
    },
    "sapateira": {
        nome: "Sapateira",
        icone: "👞",
        categoria: "quarto",
        complexidade: "baixa",
        tempoMin: 30,
        tempoMax: 60,
        precoMin: 90,
        precoMax: 180,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Sapateiras com portas de correr precisam de ajuste fino nos trilhos."
    },
    "mesa-cabeceira": {
        nome: "Mesa de Cabeceira",
        icone: "🛏️",
        categoria: "quarto",
        complexidade: "baixa",
        tempoMin: 20,
        tempoMax: 40,
        precoMin: 80,
        precoMax: 120,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Montagem rápida. Ideal para combinar com outros móveis do quarto."
    },
    "cozinha-modulada": {
        nome: "Cozinha Modulada",
        icone: "🍳",
        categoria: "cozinha",
        complexidade: "alta",
        tempoMin: 300,
        tempoMax: 900,
        precoMin: 500,
        precoMax: 900,
        permiteFixacao: true,
        permiteRecortes: true,
        observacao: "Recortes para pia, cooktop e ajustes hidráulicos podem alterar o tempo de execução."
    },
    "balcao": {
        nome: "Balcão de Cozinha",
        icone: "🍽️",
        categoria: "cozinha",
        complexidade: "media",
        tempoMin: 90,
        tempoMax: 180,
        precoMin: 150,
        precoMax: 300,
        permiteFixacao: true,
        permiteRecortes: true,
        observacao: "Recortes para cuba e torneira aumentam o tempo de instalação."
    },
    "armario-aereo": {
        nome: "Armário Aéreo",
        icone: "🗄️",
        categoria: "cozinha",
        complexidade: "media",
        tempoMin: 60,
        tempoMax: 150,
        precoMin: 120,
        precoMax: 250,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Fixação na parede é obrigatória. Verifique tubulações antes de furar."
    },
    "rack": {
        nome: "Rack para TV",
        icone: "📺",
        categoria: "sala",
        complexidade: "media",
        tempoMin: 60,
        tempoMax: 180,
        precoMin: 180,
        precoMax: 380,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Racks com portas de vidro ou iluminação exigem cuidado redobrado."
    },
    "painel-tv": {
        nome: "Painel para TV",
        icone: "🖥️",
        categoria: "sala",
        complexidade: "media",
        tempoMin: 120,
        tempoMax: 240,
        precoMin: 180,
        precoMax: 450,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Fixação na parede é essencial. Verifique o tipo de parede antes da instalação."
    },
    "mesa-jantar": {
        nome: "Mesa de Jantar",
        icone: "🍽️",
        categoria: "sala",
        complexidade: "media",
        tempoMin: 60,
        tempoMax: 180,
        precoMin: 150,
        precoMax: 350,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Mesas extensíveis possuem mecanismos que exigem atenção na montagem."
    },
    "estante": {
        nome: "Estante",
        icone: "📚",
        categoria: "sala",
        complexidade: "baixa",
        tempoMin: 40,
        tempoMax: 120,
        precoMin: 120,
        precoMax: 200,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Estantes altas devem ser fixadas na parede por segurança."
    },
    "escrivaninha": {
        nome: "Escrivaninha",
        icone: "✏️",
        categoria: "escritorio",
        complexidade: "baixa",
        tempoMin: 60,
        tempoMax: 120,
        precoMin: 150,
        precoMax: 280,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Escrivaninhas com gavetas ou nichos exigem mais atenção na montagem."
    },
    "home-office": {
        nome: "Home Office Completo",
        icone: "💻",
        categoria: "escritorio",
        complexidade: "alta",
        tempoMin: 240,
        tempoMax: 480,
        precoMin: 400,
        precoMax: 800,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Conjuntos incluem mesa, gaveteiro e prateleiras. Tempo varia conforme peças."
    },
    "mesa-escritorio": {
        nome: "Mesa de Escritório",
        icone: "💼",
        categoria: "escritorio",
        complexidade: "media",
        tempoMin: 60,
        tempoMax: 180,
        precoMin: 180,
        precoMax: 350,
        permiteFixacao: false,
        permiteRecortes: false,
        observacao: "Mesas com passagem de fios e suporte para CPU exigem atenção extra."
    },
    "nicho": {
        nome: "Nicho Decorativo",
        icone: "📦",
        categoria: "geral",
        complexidade: "baixa",
        tempoMin: 20,
        tempoMax: 40,
        precoMin: 60,
        precoMax: 120,
        permiteFixacao: true,
        permiteRecortes: false,
        observacao: "Nichos com iluminação embutida exigem cuidado com instalação elétrica."
    }
};

var fatoresAjuste = {
    usado: { multiplicador: 1.2, descricao: "Móveis usados podem exigir ajustes extras ou substituição de ferragens." },
    desmontagem: { adicionalTempo: 60, adicionalPreco: 80, descricao: "A desmontagem prévia adiciona tempo e cuidado ao serviço." },
    remontagem: { adicionalTempo: 30, adicionalPreco: 50, descricao: "A remontagem exige organização adicional das peças." },
    fixacaoParede: { adicionalTempo: 20, adicionalPreco: 30, descricao: "Fixação na parede é essencial para segurança em móveis altos." },
    recorte: { adicionalTempo: 40, adicionalPreco: 60, descricao: "Recortes para pia, tomadas ou rodapés exigem ferramentas específicas." },
    multiplosMoveis: { desconto: 0.1, descricao: "Desconto de 10% para múltiplos móveis no mesmo ambiente." }
};

var fatorLocalizacao = {
    "valparaiso": { multiplicador: 1.0, descricao: "Valparaíso de Goiás" },
    "jardim-inga": { multiplicador: 1.0, descricao: "Jardim Ingá" },
    "novo-gama": { multiplicador: 1.05, descricao: "Novo Gama" },
    "cidade-ocidental": { multiplicador: 1.05, descricao: "Cidade Ocidental" },
    "luziania": { multiplicador: 1.08, descricao: "Luziânia" },
    "gama": { multiplicador: 1.08, descricao: "Gama DF" },
    "outro": { multiplicador: 1.1, descricao: "Outra localidade" }
};
